INSERT INTO AUTOR (ID, NOME) VALUES (1, 'Silvio Santos');
INSERT INTO AUTOR (ID, NOME) VALUES (2, 'Gugu Liberato');
INSERT INTO AUTOR (ID, NOME) VALUES (3, 'Fausto Silva');


INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS, AUTOR_ID ) VALUES ( 1,' Use a cabeça Java',300, 1 );
INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS, AUTOR_ID ) VALUES ( 2,' Java como programar',500, 2 );
INSERT INTO  LIVRO ( ID, NOME, QUANTIDADE_PAGINAS, AUTOR_ID ) VALUES ( 3,' Spring boot',200, 3 );